name: Maven Build

on:
  pull_request:
  push:

jobs:
  build:
    name: Maven Build

    runs-on: ${{ matrix.os }}

    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          cache: 'maven'

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: mvn test (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: |
          mvn -B -T1C --fail-at-end clean test
        shell: bash

      - name: mvn test (Windows)
        if: runner.os == 'Windows'
        run: |
          mvn -B -T1C --fail-at-end clean test
        shell: cmd

      - name: JUnit Tests (dorny/test-reporter@v1, ${{ runner.os }})
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JUnit Tests (dorny/test-reporter@v1, ${{ runner.os }})
          # Comma-separated values.
          path: "**/target/surefire-reports/TEST-*.xml, **/build/test-results/{test,functionalTest}/TEST-*.xml"
          reporter: java-junit

        # Uses Docker, that's why Linux-only.
      - name: Unit Test Results (EnricoMi/publish-unit-test-result-action, Linux)
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ runner.os == 'Linux' }}
        with:
          files: "**/target/surefire-reports/TEST-*.xml"

      - name: Unit Test Results (EnricoMi/publish-unit-test-result-action, Windows)
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: ${{ runner.os == 'Windows' }}
        with:
          files: "**/target/surefire-reports/TEST-*.xml"
