# The name of the workflow, as shown in the list of workflows.
name: 'diKTat Check'

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  diktat_check:
    # The name of the job within the workflow.
    name: 'diKTat Check'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: 'diKTat Check using a GitHub Action'
        uses: 0x6675636b796f75676974687562/benedikt@master
