name: 'diKTat Check, Mac OS X, default settings'

on:
  workflow_dispatch:

jobs:
  diktat_check:
    name: 'diKTat Check'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'diKTat Check using a GitHub Action'
        uses: 0x6675636b796f75676974687562/benedikt@master
