name: 'diKTat Check, Ubuntu Linux (customizable input path)'

on:
  workflow_dispatch:
    inputs:
      input-paths:
        description: >
          An Ant-style path pattern which indicates the files or directories to
          check.
        type: string
        default: '**/*.kt'
        required: false
      fail-on-error:
        description: 'Treat linter errors as fatal'
        type: boolean
        default: false
        required: false

jobs:
  diktat_check:
    name: 'diKTat Check'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: diktat
        name: 'diKTat Check using a GitHub Action'
        uses: 0x6675636b796f75676974687562/benedi.kt@master
        with:
          input-paths: ${{ inputs.input-paths }}
          fail-on-error: ${{ inputs.fail-on-error }}

      - name: 'Read the exit code of diKTat'
        if: ${{ always() }}
        run: echo "diKTat exited with code ${{ steps.diktat.outputs.exit-code }}"
        shell: bash
