# The name of the workflow, as shown in the list of workflows.
name: 'diKTat Check, matrix'

on:
  workflow_dispatch:
    inputs:
      fail-on-error:
        description: 'Whether linter errors are considered fatal'
        type: boolean
        default: false
        required: false

jobs:
  diktat_check:
    # The name of the job within the workflow.
    name: 'diKTat Check'
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v3

      - name: 'diKTat Check using a GitHub Action'
        uses: 0x6675636b796f75676974687562/benedikt@master
        with:
          fail-on-error: ${{ inputs.fail-on-error }}
