name: 'diKTat Check, Mac OS X, release'

on:
  workflow_dispatch:

jobs:
  diktat_check:
    name: 'diKTat Check'
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: 'diKTat Check using a GitHub Action'
        uses: saveourtool/benedikt@v1
        with:
          debug: ${{ false }}
